There was a very minor error with argv in HLiam, but this revealed a much bigger mistake on my part.
I hadn't thought of what would happen when other people would send me patches, and how they would
figure out my baroque testing regime.

So I've updated my Makefile, testing stuff and so on, so that it's a bit more foolproof. Once the
git hooks are in place, you shouldn't be able to commit untested things. Furthermore, if the
git hooks aren't in place, I should get some sort of indication that this is happening, via the
commit message.
commit-msg approval for sebastienloisel on 2020.03.08-21:23:03

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -1,8 +1,18 @@
-#!/bin/bash
+#!/bin/bash -e
 exec 1>&2
-if make; then
-	echo "pre-commit: success"
-	exit 0
+myerr(){
+	echo -e "\033[31m\033[1mpre-commit: ERROR: $@\033[0m"
+}
+if make -q; then
+	true
+else
+	myerr 'Outdated Makefile targets found. run "make".'
+	exit 1
 fi
-echo "pre-commit: ERROR. git commit is aborting."
-exit 1
+if git diff --quiet; then
+	true
+else
+	myerr 'Unstaged changes found. run "git add".'
+	exit 1
+fi
+exit 0
